FROM node:22-alpine
WORKDIR /app
COPY server/package*.json ./
RUN npm ci
COPY server/prisma ./prisma
RUN npx prisma generate
COPY server/src ./src
RUN npm run build
EXPOSE 3001
CMD ["node", "dist/index.js"]
